### ISSUE TITLE
Render option to bind a `this`

### ISSUE THREAD

**Issue by pauleveritt** [jeasx/jsx-async-runtime#1]
I've been enjoying using `jsx-async-runtime` with 11ty. One pattern I'd be interested in: binding the original `this` to each subcomponent rendering. This would help avoid prop drilling. Let me explain.

In 11ty, the "template" renders a page. The template has [some state bound to it](https://github.com/11ty/eleventy/blob/69b02bcca9c1556e979d3d505d9e9c7712b4e07e/src/Engines/Custom.js#L188) using `.bind`, which means templates have access to configured functions and data. 

Shortcodes (i.e. subcomponents) also have a [bound `this`](https://www.11ty.dev/docs/shortcodes/#scoped-data-in-shortcodes).

While I have access to the Eleventy-provide `this` in the original template, I don't for any subcomponents. This means I need to pass the universe down through props.

It would be nice if `renderToString` allowed an option `bind=this`. Then, each subcomponent rendering would do a `bind()`.

**Comment by jablonski** [comment]
Can you provide a minimal example project which I can use to test the implementation?

**Comment by pauleveritt** [comment]
Would it help if I had a repo showing this binding idea using `preact-render-to-string`?

**Comment by jablonski** [comment]
Yes, any example would help.

**Comment by pauleveritt** [comment]
Sorry for the delay.  Here's [a tiny repo](https://github.com/pauleveritt/eleventy-jsx-async-runtime) showing how it works with Preact and 11ty.

This might be easier: a [2m30s video walkthrough](https://youtu.be/3y1-tuk2Z9E).

**Comment by jablonski** [comment]
The walkthrough helps, thanks! The repo seems to be private, maybe you can change access rights.

**Comment by pauleveritt** [comment]
@jablonski My apologies! Fixed on the repo.

**Comment by jablonski** [comment]
@pauleveritt Thanks, I've got the idea and have a working implementation now. I'm going to do some more tests tomorrow before pushing a release. But I'm quite confident that it is working as expected.

**Comment by jablonski** [comment]
Here is an example how to bind the 11ty-context in your project:

`const result = await jsxToString.call({ context: data }, content);`

**Comment by jablonski** [comment]
The changes are published in 0.4.0. Works as expected in 11ty and is a cool improvement for Jeasx (https://www.jeasx.dev/), too. Thanks a lot for raising the issue.

**Comment by pauleveritt** [comment]
Thanks a *bunch* for doing this. I'll try it today.

**Comment by pauleveritt** [comment]
I have another feature kind of thing to ask about. It's not a bug. Should you open `Discussions` or is it ok for me to file a ticket?

**Comment by jablonski** [comment]
Ticket is fine.
